#!/usr/bin/env python3
"""
Script for concatenating files into a copy-paste buffer for iterative development.

This script allows you to easily concatenate multiple files into a single copy-paste buffer,
which can be pasted into a chat interface with ChatGPT. It is particularly useful when you
need to provide code context to ChatGPT.

Usage: python script.py [file1] [file2] ...

Example: python script.py src/*

After running the script, the concatenated file contents will be copied to the clipboard.
You can then paste the clipboard contents into ChatGPT for further use.

Key Bindings:
  ? or h: Show the help screen
  Enter: Perform an action on selected files
  Space: Toggle selection of current file
  c: Check all files
  s: Uncheck all files
  t: Toggle selection of files
  q or esc: Exit the program

Author: Filipe Almeida <filipe.almeida@gmail.com>
 
"""

from pathlib import Path
import argparse
import pyperclip
import sys
import tiktoken
import urwid

def comment_style(file):
    return '#' if Path(file).suffix in ['.py', '.rb', '.r', '.sh', '.pl', '.php'] else '//'

def concatenate_files(files):
    file_contents = [f"{comment_style(f)} File {f}\n{Path(f).read_text()}" for f in files]
    return "\n".join(file_contents)

# List available tiktoken encodings
def list_encoding_names():
    enc_names = tiktoken.list_encoding_names()
    print("Available encodings:")
    for name in enc_names:
        print(name)


def main():
    parser = argparse.ArgumentParser(description='Script for concatenating files into a copy-paste buffer for iterative development.')
    parser.add_argument('files', nargs='+', help='Files to concatenate')
    parser.add_argument('-n', '--disable-ui', action='store_true', help='Disable UI and concatenate all files')
    parser.add_argument('-o', '--stdout', action='store_true', help='Use stdout instead of the copy/paste buffer')
    parser.add_argument('-l', '--list', action='store_true', help='List available encodings')
    parser.add_argument('-e', '--encoding', default='cl100k_base', help='Set the encoding')

    args = parser.parse_args()
    encoding = tiktoken.get_encoding(args.encoding)
    concatenated_content = [""]

    if args.list:
        list_encoding_names()
        sys.exit(0)

    concatenated_content = [concatenate_files(args.files)]

    if not args.disable_ui:
        def exit_on_q(key):
            if key in ('q', 'Q', 'esc'):
                raise urwid.ExitMainLoop()
            elif key in ('?', 'h'):
                show_help_overlay()

        def show_help_overlay():
            help_text = urwid.Text("    Key Bindings:")
            key_bindings_text = urwid.Text("""
              ? or h: Show this help screen
              Enter: Perform action on selected files
              Space: Toggle selection of current file
              c: Check all files
              s: Uncheck all files
              t: Toggle selection of files""")
            help_padding = urwid.Padding(urwid.Pile([help_text, key_bindings_text]), align='center')
            help_frame = urwid.Frame(urwid.Filler(help_padding), focus_part='body')
            loop.widget = help_frame

        def update_token_count(checkbox=None, new_state=None):
            selected = []
            for checkbox in checkboxes:
                if checkbox.get_state():
                    selected.append(checkbox.get_label())
            content = concatenate_files(selected)

            words = len(content.split())
            tokens = len(encoding.encode(content))
            token_count.set_text(f"Tokens: {tokens} Words: {words}")

        def get_selected():
            selected = []
            for checkbox in checkboxes:
                if checkbox.get_state():
                    selected.append(checkbox.get_label())
            concatenated_content[0] = concatenate_files(selected)

            raise urwid.ExitMainLoop()

        class CustomCheckBox(urwid.CheckBox):
            _metaclass_ = urwid.MetaSignals
            signals = ['close']

            def keypress(self, size, key):
                if key == 'enter':
                    get_selected()
                elif key == 'c':
                    for checkbox in checkboxes:
                        checkbox.set_state(False)
                elif key == 's':
                    for checkbox in checkboxes:
                        checkbox.set_state(True)
                elif key == 't':
                    for checkbox in checkboxes:
                        checkbox.set_state(not checkbox.get_state())
                elif key in ('?', 'h'):
                    show_help_overlay()
                else:
                    return super().keypress(size, key)

        checkboxes = [CustomCheckBox(f, True) for f in args.files]

        def back_to_main(_):
            loop.widget = frame

        for checkbox in checkboxes:
            urwid.connect_signal(checkbox, 'close', back_to_main)
            urwid.connect_signal(checkbox, 'postchange', update_token_count)

        token_count = urwid.Text("")

        listwalker = urwid.SimpleFocusListWalker(checkboxes)
        listbox = urwid.ListBox(listwalker)
        frame = urwid.Frame(listbox, footer=token_count)

        update_token_count()

        loop = urwid.MainLoop(frame, unhandled_input=exit_on_q)
        loop.run()

    if args.stdout:
        print(concatenated_content[0])
    else:
        pyperclip.copy(concatenated_content[0])

if __name__ == '__main__':
    main()
